### ISSUE TITLE
WARN  deprecated: .Sites.First was deprecated

### ISSUE THREAD

**Issue by fintinc** [thuliteio/seo#22]
## Description

WARN  deprecated: .Sites.First was deprecated in Hugo v0.127.0 and will be removed in a future release. Use .Sites.Default instead.

layouts/partials/seo/translations.html

line 4: `.First` should be replaced by `.Default`

```
{{- if .IsTranslated }}
  {{- range .AllTranslations.Reverse }}
    <link rel="alternate" hreflang="{{ .Language.Lang }}" href="{{ .Permalink }}">
    {{- if eq .Language.Lang .Sites.First.Language.Lang }}
      <link rel="alternate" hreflang="x-default" href="{{ .Permalink }}">
    {{- end }}
  {{- end }}
{{- end }}
```

 

### Environment

Paste the information here as shown by:

```bash
hugo v0.136.3+extended
```

**Comment by h-enk** [comment]
Thanks!
